export const CART_ACTIONS = {
    ADD_ITEM: 'ADD_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM',
    INCREMENT_ITEM: 'INCREMENT_ITEM',
    DECREMENT_ITEM: 'DECREMENT_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    DELETE_ALL: 'DELETE_ALL',
}